title: Victoria Bozo
description: 
logo: /assets/img/headshot_circle.png
description: QA Engineer
show_download: true
google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
